### ISSUE TITLE
[Feature Request] Upload Slices JSON from file

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#134]
Issue Description
-----------------

There is going to be a command line utility that generates slices. We want to be able to use the slices generated by this utility in the web viewer.

Proposed Solution
-----------------

Add an option to upload slices directly, instead of a QASM file, possibly in dev mode (#126)

**Comment by Keelando** [comment]
This was mostly covered in #138 but perhaps we want some metadata at the top of outputted slices? Theoretically it could include all of the compilation stages data too, like circuit, pauli rotations, etc. @gwwatkin

**Comment by Keelando** [comment]
@gwwatkin was there anything else you wanted implemented under this issue?

**Comment by gwwatkin** [comment]
I think it's great as is. Been using it all day😀😀😀

**Comment by gwwatkin** [comment]
Tasteful how you implemented it with the auto detect of the format. Doesn't need to be in dev mode.
