### ISSUE TITLE
[BUG] Slice selector breaks with a lot of slices

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#153]
Issue Description
-----------------

Trying to explore a computation with 10k slices. The selector bereaks.

How to Reproduce
----------------

Upload a big JSON with 10k lines or use a script to duplicate slices until you have 10k.

### Error Output

![image](https://user-images.githubusercontent.com/36427091/155709316-0ab52e52-f981-4e20-89c3-2d1277d7747a.png)
5k pixels to the right:
![image](https://user-images.githubusercontent.com/36427091/155709428-38ef1ffb-584f-4e04-a210-a956e8ecc8fd.png)

**Comment by Keelando** [comment]
We definitely need to implement the result sharing feature, I'm just not sure the best way to do it yet without server side rendering. Can you email a file, or upload a circuit or two to the public folder?

**Comment by Keelando** [comment]
Legend. I didn't initially understand that the files you deal with are non-trivial to generate and so large. Thanks for that

**Comment by gwwatkin** [comment]
Yep I'm generating them with [liblsqecc](https://github.com/latticesurgery-com/liblsqecc)
