### ISSUE TITLE
Setting up CI/CD with Github Actions 

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/web-ui#19]
Per discussion with @gwwatkin 

We would like to setup CI/CD workflows (like with [our compiler repo](https://github.com/latticesurgery-com/lattice-surgery-compiler)). Ideas:
* Prettier: https://prettier.io/
* Automate testing with Jest? - personally I don't have any experience with this.
* Auto-deploy to s3 - see https://github.com/marketplace/actions/s3-deploy

**Comment by Keelando** [comment]
Prettier looks neat. I guess we have to decide on standards? Is there a way to synchronize settings, so that everyone has an exact copy, and agreed-upon changes propagate to the central "source of truth?" I am not sure how it works, though I have just installed it anyway.

Haven't heard about Jest but I'll look into it

I've used S3 for image hosting but will have to look into auto-deploy on S3. Sounds like that's what we have to do to go serverless.

**Comment by alexnguyenn** [comment]
@Keelando I haven't looked into it too deeply, but if it is anything like [Black](https://github.com/psf/black) for Python then we can have a file that store the settings for the project - like [pyproject.toml](https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/dev/pyproject.toml) for the compiler repo. It is an opinionated formatter so I don't think we need to change that much anyway. 

We will use a CI tool to do the check for Prettier for every pull requests (you can see recent PRs from the compiler repo for an example). @gwwatkin apparently pre-commit supports Prettier as well.

I think me and @gwwatkin will be able to look into auto-deployment. It does seem to be quite straightforward with Github Actions from the examples I have seen.

**Comment by gwwatkin** [comment]
@Keelando and @alexnguyenn 
Here is my experience:
 * Linters: Prettier looks interesting. I've used [ESLint](https://typescript-eslint.io/). It does a pretty good job at doing static analysis on your code,but it might be obsolete with typescript.  Also, unlike for the JS version, for which there is a pre-commit hook, I can't find one for the typescript version ... still might be worth having a look. I would avoid it if it prevents us from running pre-commit.ci.
 * Yes prettier has a [.prettierrc](https://prettier.io/docs/en/configuration.html) configuration file like pyproject.toml
 * Yes, I've suggested in the past we use s3 to deploy, but we don't necessarily have to - that's the beauty of having separated the API, we can  host anywhere, including github pages if we want to - I'm open to better ideas. S3 is cheap, flexible and powerful, but it might need some complex configuration, especially if we want a deployment for every PR. Though there are a lot of examples, such as the one Alex pointed out.

**Comment by gwwatkin** [comment]
I was forgetting, testing with Jest should be straightforward. Looks like a simple action is enough, like [this one](https://github.com/marketplace/actions/run-jest). They use yarn ... not sure if we have to change it `npm`, probably not.

**Comment by gwwatkin** [comment]
One more thing I might suggest is that if we add `dev` branch, we deploy it to `dev.latticesurgery.com`

**Comment by alexnguyenn** [comment]
@gwwatkin @Keelando So I have looked around a little bit. Seems like Prettier + ESLint is a commonly used option. Here are some guides I have found:
* Example repo: https://github.com/samfromaway/Typescript-ES-Lint-Template
* https://moduscreate.com/blog/lint-style-typescript/
* https://khalilstemmler.com/blogs/tooling/prettier/

For pre-commit hooks we can use [husky](https://github.com/typicode/husky). I have looked at some examples and can definitely create a Github Action workflow to have those checks running for our CI like the compiler repo. We can also bring over Dependabot to help manage our dependencies as well.

**Comment by gwwatkin** [comment]
I think these are all desirable features, we just have to decide how soon do we need  them and who will implemented. I'm happy with @alexnguyenn going for it since you did an awesome job on the LSC repo, but I can also give it a shot after the 13th

**Comment by alexnguyenn** [comment]
Closes via #36
