### ISSUE TITLE
Example Circuits

### ISSUE THREAD

**Issue by Keelando** [latticesurgery-com/web-ui#32]
Re-implement example circuits selection for demo purposes.

Another idea is to render the input circuit visually as text (for now) while the compilation computes its output.

As I understand, we are using Qiskit to render the circuit as an ascii text image? Perhaps we can separate the input circuit rendering from the current request payload, so that the input circuit rendering can occur first (or in parallel) while the compilation is processing?

This would involve changes on the lambda. It might be nice for the user to have something to look at while the compilation is working, as it sometimes takes 5 to 10 seconds for the response to come back.

**Comment by alexnguyenn** [comment]
Closed by #40
