### ISSUE TITLE
Fix navbar

### ISSUE THREAD

**Issue by Keelando** [latticesurgery-com/web-ui#37]
Navbar is broken on live website.

Navbar uses CSS/Javascript to open close which is incompatible with React's component rendering paradigm.

Replace Navbar with react component.

Alternatively, we can scrap the navbar if anyone wants. It won't take long to fix it, so I'll go ahead and do that.

**Comment by alexnguyenn** [comment]
I think navbar will be needed as we start to add more content to the page.
