### ISSUE TITLE
Latest PR broke latticesurgery.com

### ISSUE THREAD

**Issue by Keelando** [latticesurgery-com/web-ui#41]
Latticesurgery.com response with an HTTP error code of 403 in the console. Somehow my latest PR may have broken the production build.

My first thought is that accessing static/public files operates differently in development than production, as it does in Django. But I'd have to see the error logs on the S3. Even if that was the case, nothing should break until you attempt to load the public assets.

**Comment by Keelando** [comment]
I think George is correct about the S3 data availability zones. Seems like its fast to deploy in the (European?) zone?

I would expect lattice surgery to become available some time tonight or tomorrow. But that's a bit of a drag that its so slow. Perhaps we should deploy in multiple zones, and then bring all offline except for one once its available worldwide? That is one proposed solution I saw on SO.

**Comment by Keelando** [comment]
Closing. Wild speculation was inaccurate. George confirmed the issue of lattice surgery dot com going white after deployment was due to Cache Invalidation on the s3

**Comment by gwwatkin** [comment]
Problem was that the cached s3 objects needed to be invalidated from CloudFront:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html
