### ISSUE TITLE
[BUG] Code duplication between SelectExampleCircuit and UploadCircuit

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#79]
Issue Description
-----------------
There is duplicate code that should exist only once and be shared among two components
### Code Snippet

Here:
https://github.com/latticesurgery-com/web-ui/blob/8165852a510a06a98bb1ebd8ba54ed869ef89ddb/src/components/sections/UploadCircuit.tsx#L39-L117

and Here:

https://github.com/latticesurgery-com/web-ui/blob/8165852a510a06a98bb1ebd8ba54ed869ef89ddb/src/components/sections/SelectExampleCircuit.tsx#L49-L127

The buttons/spinners are also duplicate and could be handled as a custom component shared among the two files

**Comment by gwwatkin** [comment]
@alexnguyenn might be a long shot but maybe on day ESLint will detect this sort of thing https://github.com/eslint/eslint/issues/3957. Though I was pretty sure we had a tool like that for C++.

**Comment by Keelando** [comment]
UploadCircuit and SelectExampleCircuit share a lot of functionality but set different state variables depending on which is called. Maybe I could use ternary operators instead? It's going to be a bit messy. Not sure what the best way forward is, which is why it hasn't been changed

**Comment by gwwatkin** [comment]
@Keelando Ternary operator sounds good. You can also parametrize a callback on a variable like `makeCallback = (param, setParam) => (callbackArgs) => { bodyOfCallback }`

I think I'm way happier with slightly more involved code than duplication. If it gets to complex you can allways break it down into smaller pieces. Fixing it will take half the time because it's all in one place 😉 a new contributor (including myself) might not even be aware that there are two places to check the way it is now 😅 I lost an hour on why a trivial change just wouldn't show up
