### ISSUE TITLE
[Feature Request] About page enhancements

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/web-ui#92]
Issue Description
-----------------
- [ ] Ask on slack, and add the advisors
- [ ] Sponsor logos (share the component with the home page?)
- [ ] Contact us at `info@latticesurgery.com`
- [ ] A "press" section with the two articles on SFU's CS and Phys websites and the one at TUM

**Comment by alexnguyenn** [comment]
Agree with those points - I will work on this during the weekend
